[Draft] Improvements to home page
dr-von-doom/Exclusive-legacy pull request #2
Opened 2024-08-29 14:16 UTC by EmilyRoldan

This pull request is still in development. I've created it as a draft to share progress and gather initial feedback.

Pending:
- Add a banner at the end
- Add products
- Create ads (Not sure if I'll do it myself or find them online)
- Make the home page responsive

2024-08-30 16:26 UTC, Sonya-c commented on img/ad-home.svg
Porfa, pon todas las imagenes en el folder `images/ads`

2024-08-30 16:28 UTC, Sonya-c commented on styles/styles.css
> +body {
A esto que es comun añade el comentario de 

```
/* ==== COMMON ==== */
```

Y cuando inicien los estilos de tu pagina haces algo asi 

```
/* ==== HOME PAGE ==== */
```

2024-08-30 16:29 UTC, Sonya-c commented on index.html
> +        <img src="img\ad-home.svg" alt="Ads" />
Usa este tio de slash `/` (Como hiciste mas adelante)

2024-08-30 16:30 UTC, Sonya-c commented on index.html
> +        <img src="img\ad-home.svg" alt="Ads" />
Ademas, intenta no usar la palabra 'ads' algunos bloqueadores de anuncios bloquean por esas palabras claves. En su lugar, en el alt usa una descripción del producto (algo sencillo), eso también mejora es SEO

2024-08-30 16:33 UTC, Sonya-c commented on styles/styles.css
> +.text-container {
Text container es una etiqueta muy general. Para evitar conflictos con los estilos. Puede añadir en el main la clase

```
<main class="home-page" > </main>
```
Y a cada estilo hacer 

```
main.home-page .selector { ... }
```

2024-08-31 06:00 UTC, daolivaress commented on index.html
> +      <section class="img-container">
Si puedes usa selectores mas específicos para evitar problemas cuando se junte todo

2024-08-31 14:18 UTC, Sonya-c commented on index.html
> +    <title>Home page</title>
```suggestion
    <title>Exclusive</title>
```

2024-08-31 14:22 UTC, Sonya-c commented on index.html
> +        <img src="images/ads/ad-home.svg" alt="Advertising image" />
Creo que podrías mejorar el alt de estas images.


```suggestion
        <img src="images/ads/ad-phone.svg" alt="IPhone 14 Series. Up to 10% off voucher. Shop now" />
        <img src="images/ads/ad-home.svg" alt="Sale. Get up to 30% off all home products. Buy now" />
```

Recuerda que alt es usado por los lectores de pantalla. Si la imagen tiene texto, sería ideal que el alt tenga el texto o una descripción de la imagen. También, en ambas imagenes parece haber links y boton para 'comprar ahora'. Ya que estas son imagenes, una buena idea sería encerrar cada imagen en un link 


```
  <a href="#"><img src="..." alt="..." /></a>
  <a href="#"><img src="..." alt="..." /></a>
```

2024-08-31 14:57 UTC, Sonya-c requested changes
Veo que has mejorado mucho. Solo son unos detallitos por pulir sobre el responsive, pero vas muy bien. Haz estos cambios y solo sería esperar el header y footer

2024-08-31 14:57 UTC, Sonya-c commented on styles/styles.css
> +
Esto te asegurara que el grid sea responsive 
```suggestion
.grid-container {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
  gap: 20px;
  margin: 20px 0;
}
```

No soy experta en grid, so si quieres saber mas: https://css-tricks.com/look-ma-no-media-queries-responsive-layouts-using-css-grid/

2024-08-31 14:57 UTC, Sonya-c commented on styles/styles.css
> +}
```suggestion
.product-box {
  display: flex;
  flex-direction: column;
  align-items: center;
  border-radius: 5px;
  background-color: var(--color-white);
  padding: 20px 0 10px 0;
  position: relative;
  border: 1px solid var(--color-grey);
  box-shadow: 1px 4px 29px -23px rgba(0, 0, 0, 0.75);
}
```

Creo que un radius menor, un box shado mas suave y  un border realmente podría hacer mas organizado el diseño. (Esta es solo una sugerencia)

2024-08-31 14:57 UTC, Sonya-c commented on index.html
> +          <h1 class="poppins-style">Everything you need, just a Click away</h1>
No creo que sea una buena idea añadir un h1 aquí, podrías usar un h3 tal vez

2024-08-31 14:57 UTC, Sonya-c commented on styles/styles.css
> +}
```suggestion
.banner-style {
  /* ==== COMMON ==== */
  background-color: var(--color-neutral-black);
  width: 100%;
  display: flex;
  flex-direction: column;
  align-items: center;
  border-radius: 20px;
  box-sizing: border-box;
  padding: 1rem;
}
```

2024-08-31 14:57 UTC, Sonya-c commented on styles/styles.css
> +}
Esto hara que se vea como columna en celulares y en desktop como fila 

```suggestion
.home-page .text-img-container {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: space-around;
  width: 100%;
}

@media (min-width: 576px) {
  .home-page .text-img-container {
    flex-direction: row;
  }
}
```

También podrías usar la clase `flex-responsive-row` que había creado

2024-08-31 14:57 UTC, Sonya-c commented on index.html
> +              </h1>
Nope, en definitiva no puede haber un h1 aquí

2024-08-31 14:57 UTC, Sonya-c commented on styles/styles.css
> +}
Este es el que esta en el banner final? podrías hacer que este centrado en mobile?

2024-08-31 14:57 UTC, Sonya-c commented on styles/styles.css
> +
Podrías hacer que solo en mobile este centrado? usando esto
```
  margin: 1rem auto; 
```

2024-08-31 14:57 UTC, Sonya-c commented on index.html
> +            <h1 class="style-shop poppins-style">Shop Now</h1>
Nooo 😭! este no puede ser un h1

2024-08-31 14:57 UTC, Sonya-c commented on index.html
> +            </svg>
Podrías encerrar todo esto en un anchor (a) (y quitar el h1 😭)

2024-08-31 14:57 UTC, Sonya-c commented on styles/styles.css
> +}
(Solo para la segunda imagen), creo que un shado mas sueve un borde clarito le quedaría melo 


```suggestion
.home-page .img-container img {
  margin: 10px;
  max-width: 100%;
  border-radius: 20px;
  /* ==== COMMON ==== */
  box-shadow: 0 4px 8px var(--color-grey);
}

.home-page .img-container img:nth-of-type(2) {
  box-shadow: 1px 4px 29px -23px rgba(0, 0, 0, 0.75);
  border: 2px solid #d8d2be;
}
```

2024-08-31 16:14 UTC, Orun1tia requested changes

2024-08-31 16:14 UTC, Orun1tia commented on styles/styles.css
> +  }
quiza añadir .home-page adelante de algunas clases en el styles que pueden no estar del todo claras que peternecen a la parte del homepage, por ejemplo

```suggestion
.home-page .icons-style {
    gap: 10px;
    margin: 0;
  }

.home-page .custom-icon {
    width: 15px;
    height: 15px;
  }
```

2024-08-31 20:09 UTC, Orun1tia approved these changes
NICE

2024-08-31 22:20 UTC, Sonya-c approved these changes

2024-09-01 01:09 UTC, DarioMejia approved these changes
Well done. Keep up with good work. Greetings.

2024-09-01 02:18 UTC, merged