[FE] UH2002: Página lista productos (PLP)
dr-von-doom/Exclusive-legacy pull request #6
Opened 2024-08-30 06:56 UTC by Sonya-c

2024-08-30 15:33 UTC, DarioMejia requested changes
The HTML structure is well-organized and adheres to semantic HTML practices, making it easy to understand and maintain. The use of <main>, <aside>, and <div> elements is appropriate for layout, and the consistent application of classes like flex-responsive-row and remove-list-styles contributes to clean, reusable styles. Excellent work.

2024-08-30 15:33 UTC, DarioMejia commented on styles/styles.css
> +  color: inherit !important;
The use of inherit in main.plp .products-list .product a ensures consistency. However, the !important should be avoided unless absolutely necessary to override styles, as it can make future maintenance difficult.

2024-08-30 15:33 UTC, DarioMejia commented on styles/styles.css
> +  margin-top: 100px;
The banner `margin-top: 100px` might create excessive spacing on smaller screens or different layouts. Consider making this value dynamic or responsive.

2024-08-30 15:33 UTC, DarioMejia commented on styles/styles.css
The structure seems solid, but consider grouping similar styles together for better readability and maintainability.

2024-08-30 15:33 UTC, DarioMejia commented on plp.html
> +    <!-- Add header  -->
Header must be inherited from UH2000.

2024-08-30 15:33 UTC, DarioMejia commented on plp.html
> +        <!-- Add breadcrumb  -->
Ensure consistency of Breadcrumb between different pages.

2024-08-30 15:33 UTC, DarioMejia commented on plp.html
> +    <!-- Add footer -->
Footer must be inherited from UH2000.

2024-08-30 18:19 UTC, daolivaress approved these changes
La estructura del HTML y los estilos esta bien y los archivos de imágenes están bien distribuidos

2024-08-31 19:54 UTC, Orun1tia approved these changes
Nice job

2024-08-31 22:34 UTC, EmilyRoldan approved these changes
nice job

2024-08-31 22:38 UTC, merged